apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: demo-sms-api
  annotations:
    avp.kubernetes.io/path: "app-credentials/credentials/data/app"
type: Opaque
stringData:
  postgres-host: <postgres-host>
  postgres-user: <postgres-user>
  postgres-name: <postgres-name>
  postgres-password: <postgres-password>