---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: demo-sms
spec:
  encryptedData:
    postgres-password: AgA3iPlqufhjWmDQotFjuYNRqMLqvfcPfflXQiahjRAGZlx8fvCEWIwuiZ6XSyM5zwmZM1mHK+Or9TSGGXrvrVsoSGoEa4XwQ26Y5FDbxqWLALHOWZRf7NYnY6Rw96Sx8uE/Tv2hVaUQuaxAoLvWmws3ZXryx2vBDAWNeVL8M/IexuWDmcjZop6w5wfaXczM8WOhHnDD0BMQK0onIaqVz0DyaOsZd2/FdnPBKqZEmMA630x7nklOVOYiKOhBTGDnbBZpTtx+KUu2ocqAZ0F9K7b19MYenXSl+gvoa/rOcSd0VjL15LEe2EgQtEXZ9mFYwvLhBV4ab64q0Bueyn0Fc1EcqYorkGpj69WSuhHSoU2Es7h1kyGKo5pUOYKgykzMO1eZkHcQ5DaKFB70WK/LNbReJxdVxRxKWvhs1wO5T36KWugCfp2KJ5eBmgxnits23e2olcW5yUxiGuycGVULa8uHVfVdJLPdP6gICNHeLKr9JwG9YGSd5DRn+oKIfbM7vMjoJCAm5KatOher21TfCV6i9Q2AGW0SjoO23IpfEvuE6ArwgqVLNJwhZiLO/x9oNwmF2V0ZL6+VV82VzALz9L9qAAJ4b50BE98gEXkgd+g69fsRdvgNoPI1F7zEcgZ2jDx/D0Bd71MxBm8bQOKst9a7SksiIol67h9M7K5KyZeVg1KU06jppMCSb/ITx+bVMfcNNkFCP4OnycZA
  template:
    metadata:
      name: postgres-secret
      namespace: demo-sms
    type: Opaque